- name: mysql component
  hosts: mysql
  become: yes
  tasks:
    - name: disable current version of mysql
      ansible.builtin.command: dnf module disable mysql -y

    - name: setup mysql 5.7 repo
      ansible.builtin.copy: 
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: install mysql server
      ansible.builtin.package:
        name: mysql-community-server
        state: present

    - name: start and enable mysql server
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: Load cities data
      community.mysql.mysql_db:
        name: shipping
        state: import
        target: /app/schema/master-data.sql
        login_host: mysql.aws76s.online
        login_user: root
        login_password: RoboShop@1


    - name: setup root password
      ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1

